In [14]:
import numpy as np # type: ignore
#1D array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [15]:
#2D array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [16]:
#3D array
c= np.array([[[1,2,3],[4,5,6,]],[[7,8,9],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [17]:
#Data Type 
p=np.array([1,2,3,4], dtype=float)
q=np.array([[1,2,3],[4,5,6]], dtype=complex)
print(p)
print(q)

[1. 2. 3. 4.]
[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [18]:
#arange()
p=np.arange(1,11,3)
q=np.arange(1,11,2)
print(p)
print(q)

[ 1  4  7 10]
[1 3 5 7 9]


In [19]:
#reshape()
p=np.arange(1,11).reshape(5,2)
q=np.arange(16).reshape(2,2,2,2)
print(p)
print()
print(q)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [20]:
#np.ones() np.zeros()
p=np.ones((3,4))
q=np.zeros((2,5))
print(p)
print()
print(q)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
#np.random()
import numpy as np
p= np.random.random((4,5))
print(p)

[[0.88740615 0.00894901 0.99172181 0.72308962 0.95720887]
 [0.40617929 0.82819485 0.25233124 0.43880724 0.20151893]
 [0.42364265 0.50390529 0.11497159 0.61863106 0.41156121]
 [0.06185104 0.50082079 0.95044826 0.99051681 0.76405767]]


In [22]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
a=np.zeros((10))
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [24]:
a=int(input("no. of rows: "))
b=int(input("no. of columns: "))
res=np.random.random((a,b))
print(res)
np.average(res)


ValueError: invalid literal for int() with base 10: ''

In [19]:
a=int(input("no. of rows: "))
b=int(input("no. of columns: "))
z=np.zeros((a,b), dtype=int)
z[0,:]=1 # top row
z[-1,:]=1 # bottom row
z[:,0]=1 # left column
z[:,-1]=1 # right column
print(z)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [25]:
# np.linespace()
p=np.linspace(0,1,10)
print(p)
print()
q=np.linspace(0,1,10)[1:-1] #excluding 0 and 1
print(q)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

[0.11111111 0.22222222 0.33333333 0.44444444 0.55555556 0.66666667
 0.77777778 0.88888889]


In [26]:
# identity matrix of(3,4)
a=int(input("no. of rows: "))
b=int(input("no. of columns: "))
res= np.zeros((a,b), dtype=int)

for i in range(min(a,b)):
    res[i,i] = 1
print(res)    

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [2]:
#itemsize
import numpy as np 
a=np.arange(8).reshape(2,2,2)
print(a)
a.itemsize

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


4

In [13]:
a=np.arange(12,dtype=float).reshape(4,3)
print(a)
print(a.dtype)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
float64


In [26]:
a1=np.arange(9).reshape(3,3)
a2=np.arange(9,18).reshape(3,3)
print(a1)
print()
print(a2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [28]:
#arithmatic oparation
print((1+a1))
print()
print((a2*3))
print()
print((a2**3))


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[27 30 33]
 [36 39 42]
 [45 48 51]]

[[ 729 1000 1331]
 [1728 2197 2744]
 [3375 4096 4913]]


In [29]:
#relational operation
print((a1>5))
print()
print((a2>35))

[[False False False]
 [False False False]
 [ True  True  True]]

[[False False False]
 [False False False]
 [False False False]]


In [32]:
#vector operation
print(a1+a2)
print()
print(a1*a2)
print()
print(a2**a1)

[[ 9 11 13]
 [15 17 19]
 [21 23 25]]

[[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]

[[          1          10         121]
 [       1728       28561      537824]
 [   11390625   268435456 -1614177151]]


In [57]:
a=np.random.random((3,3))
print(a)


[[0.54126828 0.81817109 0.65777421]
 [0.92692709 0.35381449 0.8602116 ]
 [0.49170977 0.45011936 0.33757426]]


In [58]:
a=np.round(a*100)
print(a)

[[54. 82. 66.]
 [93. 35. 86.]
 [49. 45. 34.]]


In [67]:
#sum/product/max/min
print(np.max(a))
print(np.min(a))
print(np.sum(a,axis=0))
print(np.prod(a,axis=0))


93.0
34.0
[196. 162. 186.]
[246078. 129150. 192984.]


In [71]:
#mean/median/std/var
print(np.mean(a,axis=0))
print(np.median(a))
print(np.std(a,axis=0))
print(np.var(a))

[65.33333333 54.         62.        ]
54.0
[19.66949132 20.2155056  21.41650454]
440.69135802469134


In [72]:
#dot product
a1=np.arange(8).reshape(2,4)
a2=np.arange(8,16).reshape(4,2)
print(a1)
print()
print(a2)
print()
print(np.dot(a1,a2))

[[0 1 2 3]
 [4 5 6 7]]

[[ 8  9]
 [10 11]
 [12 13]
 [14 15]]

[[ 76  82]
 [252 274]]


In [78]:
#log & exp
a=np.random.random((3,3))
print(a)
print()
print(np.log(a))
print()
print(np.exp(a))

[[0.03571276 0.5679562  0.59880712]
 [0.52384648 0.82214024 0.51815735]
 [0.66275665 0.9680164  0.18978499]]

[[-3.33224715 -0.56571097 -0.51281573]
 [-0.64655662 -0.1958443  -0.65747631]
 [-0.4113474  -0.03250625 -1.66186346]]

[[1.03635812 1.76465677 1.81994653]
 [1.68850999 2.27536445 1.67893112]
 [1.94013324 2.63271702 1.20898963]]


In [82]:
#round/floor/ceil
a=np.random.random((4,2))
print(a)
print()
print(np.round(a*100))
print()
print(np.floor(a))
print()
print(np.ceil(a))

[[0.08103991 0.22869992]
 [0.78935148 0.08891135]
 [0.12569319 0.12382842]
 [0.37391418 0.08682659]]

[[ 8. 23.]
 [79.  9.]
 [13. 12.]
 [37.  9.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [85]:
a1=np.arange(9,dtype=int).reshape(3,3)
a2=np.arange(27,dtype=int).reshape(3,3,3)
print(a1)
print()
print(a2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [100]:
#indexing and slicing
print(a1[1,2])
print()
print(a1[1,])
print()
print(a1[1:,1:])
print()
print(a1[1:,2])
print()
print(a1[1:,::2])
print()
print(a1[::2,0::])
print()
print(a1[0::2,0::2])

5

[3 4 5]

[[4 5]
 [7 8]]

[5 8]

[[3 5]
 [6 8]]

[[0 1 2]
 [6 7 8]]

[[0 2]
 [6 8]]


In [108]:
print(a2[2,0::,0::])
print()
print(a2[2,1,0::2])
print()
print(a2[1,0::2,0::2])
print()

[[18 19 20]
 [21 22 23]
 [24 25 26]]

[21 23]

[[ 9 11]
 [15 17]]



In [111]:
#iteration
print(a2)
print()
for i in a2:
    print(i)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [113]:
#transpose/ravel
a=np.arange(10,dtype=int).reshape(5,2)
print(a)
print()
print(np.transpose(a))
print()
print(np.ravel(a))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

[[0 2 4 6 8]
 [1 3 5 7 9]]

[0 1 2 3 4 5 6 7 8 9]


In [116]:
#stacking
a1=np.arange(9,dtype=float).reshape(3,3)
a2=np.arange(9,18,dtype=float).reshape(3,3)
print(a1)
print()
print(a2)
print()
print(np.hstack((a1,a2)))
print()
print(np.vstack((a1,a2)))

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]

[[ 9. 10. 11.]
 [12. 13. 14.]
 [15. 16. 17.]]

[[ 0.  1.  2.  9. 10. 11.]
 [ 3.  4.  5. 12. 13. 14.]
 [ 6.  7.  8. 15. 16. 17.]]

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]
 [12. 13. 14.]
 [15. 16. 17.]]


In [1]:
#Splitting
import numpy as np
a1=np.arange(16,dtype=float).reshape(4,4)
print(a1)
print()
print(np.hsplit(a1, 2))
print()
print(np.vsplit(a1, 2))

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]

[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]

[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]


In [15]:
#fancy indexing
a=np.arange(12,dtype=int).reshape(4,3)
print(a)
print()
print(a[[0,1,3]])
print()
print(a[[0,2,3],0:2])
print()
print(a[:,[0,2]])


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  1  2]
 [ 3  4  5]
 [ 9 10 11]]

[[ 0  1]
 [ 6  7]
 [ 9 10]]

[[ 0  2]
 [ 3  5]
 [ 6  8]
 [ 9 11]]


In [16]:
x=np.random.randint(1,100,24).reshape(6,4)
print(x)

[[33 88  9 21]
 [28 77 83 98]
 [74 71 43 52]
 [82 30  2 96]
 [31  4 13 26]
 [50 26 26 27]]


In [21]:
#boolean indexing
print(x[x>50])
print()
print(x[x%2==0])
print()
print(x[(x>50) & (x%2==0)])
print()
print(x[~(x%2==0)])

[88 77 83 98 74 71 52 82 96]

[88 28 98 74 52 82 30  2 96  4 26 50 26 26]

[88 98 74 52 82 96]
[33  9 21 77 83 71 43 31 13 27]


In [2]:
#broadcasting
# 1.  make two array have the same dimension if dimension of two array different, then add 1 on the head
# 2. increase the dimension to the same level imp(only if we can place 1 in dimension or 1 is present in dimension)

In [4]:
import numpy as np
a1=np.arange(4).reshape(2,2)
a2=np.arange(2).reshape(2)
print(a1)
print()
print(a2)
print()
print(a1+a2)

[[0 1]
 [2 3]]

[0 1]

[[0 2]
 [2 4]]


In [5]:
a1=np.arange(8).reshape(4,2)
a2=np.arange(4).reshape(4)#here it gets (1,4)=>(4,4) != (4,2)
print(a1)
print()
print(a2)
print()
print(a1+a2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]

[0 1 2 3]



ValueError: operands could not be broadcast together with shapes (4,2) (4,) 

In [6]:
a1=np.arange(8).reshape(4,2)
a2=np.arange(2).reshape(2)
print(a1)
print()
print(a2)
print()
print(a1+a2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]

[0 1]

[[0 2]
 [2 4]
 [4 6]
 [6 8]]


In [7]:
a1=np.arange(8).reshape(4,2)
a2=np.arange(4).reshape(2,2)#no 1 is present so dimension cannot be matched
print(a1)
print()
print(a2)
print()
print(a1+a2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]

[[0 1]
 [2 3]]



ValueError: operands could not be broadcast together with shapes (4,2) (2,2) 

In [7]:
#sigmoid function
import numpy as np
a= np.random.randint(0,20,20).reshape(4,5)
print(a)

def sigmoid(array):
    return 1/(1+ np.exp((-array)))

sigmoid(a)

[[ 2 15 14 10  8]
 [14  7  9  5 10]
 [ 6 13 15 13  4]
 [18 13  5 17 15]]


array([[0.88079708, 0.99999969, 0.99999917, 0.9999546 , 0.99966465],
       [0.99999917, 0.99908895, 0.99987661, 0.99330715, 0.9999546 ],
       [0.99752738, 0.99999774, 0.99999969, 0.99999774, 0.98201379],
       [0.99999998, 0.99999774, 0.99330715, 0.99999996, 0.99999969]])

In [9]:
#mean square 
actual=np.random.randint(0,20,10)
predicted=np.random.randint(0,20,10)
print(actual)
print()
print(predicted)
print()

def MSE(actual,predicted):
    return np.mean((actual-predicted)**2)
MSE(actual,predicted)

[17 11 13 10  7  9  3  2 13  0]

[14 13 17 19 13 12  6  2  5 10]



32.8

In [13]:
#working with missing value
a=np.array([10,20,30,40,np.nan,60,70,80,90])
print(a)
print()
#np.isnan()
print(np.isnan(a))
print()
print(a[np.isnan(a)])
print()
print(a[~np.isnan(a)])

[10. 20. 30. 40. nan 60. 70. 80. 90.]

[False False False False  True False False False False]

[nan]

[10. 20. 30. 40. 60. 70. 80. 90.]


In [18]:
#sort()
a=np.random.randint(0,25,10)
print(a)
print()
print(np.sort(a))
print()
print(np.sort(a)[::-1])

b=np.random.randint(1,20,20).reshape(4,5)
print()
print(b)
print()
print(np.sort(b))
print()
print(np.sort(b,axis=0))#of column
print()
print(np.sort(b,axis=1))#of row

[ 8 21 18  8  4  6  2  8 20 11]

[ 2  4  6  8  8  8 11 18 20 21]

[21 20 18 11  8  8  8  6  4  2]

[[ 4  4 13 14  5]
 [ 7 16 18  5 12]
 [14  2  1  9  5]
 [12  6 19  2  1]]

[[ 4  4  5 13 14]
 [ 5  7 12 16 18]
 [ 1  2  5  9 14]
 [ 1  2  6 12 19]]

[[ 4  2  1  2  1]
 [ 7  4 13  5  5]
 [12  6 18  9  5]
 [14 16 19 14 12]]

[[ 4  4  5 13 14]
 [ 5  7 12 16 18]
 [ 1  2  5  9 14]
 [ 1  2  6 12 19]]


In [42]:
#np.append()
a=np.random.randint(0,20,10)
print(a)
print()
print(np.append(a,50))
b=np.random.randint(0,10,9).reshape(3,3)
print()
print(b)
print()
print(np.append(b,np.array([[1,2,3]]),axis=0))#in row
print()
print(np.append(b,np.array([[1],[2],[3]]),axis=1))#in column

[16  4 18 12  1  2  6  2 17  3]

[16  4 18 12  1  2  6  2 17  3 50]

[[2 2 7]
 [3 5 7]
 [7 4 0]]

[[2 2 7]
 [3 5 7]
 [7 4 0]
 [1 2 3]]

[[2 2 7 1]
 [3 5 7 2]
 [7 4 0 3]]


In [44]:
a=np.random.randint(0,20,16).reshape(4,4)
b=np.random.randint(0,20,16).reshape(4,4)

print(np.concatenate((a,b),axis=0))#column
print()
print(np.concatenate((a,b),axis=1))#row

[[ 9  5  8  2]
 [ 8  0  8  3]
 [18  7  9  8]
 [ 1  7 12 14]
 [16  4 16  5]
 [ 7  2 15  1]
 [15 10 15 17]
 [18  9 14  5]]

[[ 9  5  8  2 16  4 16  5]
 [ 8  0  8  3  7  2 15  1]
 [18  7  9  8 15 10 15 17]
 [ 1  7 12 14 18  9 14  5]]


In [45]:
#np.unique()
a=np.array([1,1,1,1,2,2,2,2,3,3,3,5,5,5,4,4,6])
print(np.unique(a))

[1 2 3 4 5 6]


In [47]:
#expand dimensions
a=np.random.randint(0,10,10)
print(a)
print(np.expand_dims(a,axis=0))
print(np.expand_dims(a,axis=1))

[8 9 9 0 1 4 9 1 8 5]
[[8 9 9 0 1 4 9 1 8 5]]
[[8]
 [9]
 [9]
 [0]
 [1]
 [4]
 [9]
 [1]
 [8]
 [5]]


In [48]:
#np.where()
a=np.random.randint(0,30,15)
print(a)
print()
print(np.where(a>20))
print()
print(np.where(a%2==0,0,1))

[15 17 29 27  5 26 21 22 29 16 23 25 23 13  3]

(array([ 2,  3,  5,  6,  7,  8, 10, 11, 12], dtype=int64),)

[1 1 1 1 1 0 1 0 1 0 1 1 1 1 1]


In [49]:
#max index and min index in array
x=np.random.randint(0,20,9).reshape(3,3)
print(x)
print()
print(np.argmax(x,axis=0))
print()
print(np.argmin(x,axis=1))

[[ 9 10  6]
 [16 18  0]
 [19  9  7]]

[2 1 2]

[2 2 2]


In [51]:
#cumulative sum and product
x=np.random.randint(0,20,9).reshape(3,3)
print(x)
print()
print(np.cumsum(x,axis=0))
print()
print(np.cumprod(x,axis=1))

[[ 8 12  0]
 [13 15  9]
 [10 10 18]]

[[ 8 12  0]
 [21 27  9]
 [31 37 27]]

[[   8   96    0]
 [  13  195 1755]
 [  10  100 1800]]


In [52]:
#corelation coefficient
x=np.random.randint(0,20,10)
y=np.random.randint(0,20,10)
print(np.corrcoef(x,y))

[[1.         0.03317117]
 [0.03317117 1.        ]]


In [56]:
# np.isin()
arr=np.random.randint(0,20,10)
item=np.random.randint(0,20,10)
print(arr)
print(item)
print(np.isin(arr,item))

[12  7 13  0  1  4 15 19  9  9]
[ 7 14 15  7 11 13  6 17  2 14]
[False  True  True False False False  True False False False]


In [58]:
#np.flip()
x=np.random.randint(0,20,9).reshape(3,3)
print(x)
print()
print(np.flip(x,axis=0))
print()
print(np.flip(x,axis=1))

[[ 6 10 10]
 [ 0 10 19]
 [ 0  2  3]]

[[ 0  2  3]
 [ 0 10 19]
 [ 6 10 10]]

[[10 10  6]
 [19 10  0]
 [ 3  2  0]]


In [63]:
#np.put()
x=np.random.randint(0,20,10)
print(x)
print(x[np.put(x,[1,2],[69,69])])

[ 5  5 13 15 10  8  6 14 13 18]
[[ 5 69 69 15 10  8  6 14 13 18]]


In [64]:
#np.delete()
x=np.random.randint(0,20,10)
print(x)
print(np.delete(x,[0,2,4]))

[ 6  3 14 16 16  7 12  9  4  5]
[ 3 16  7 12  9  4  5]


In [65]:
x=np.random.randint(0,20,10)
y=np.random.randint(0,20,10)
print(x)
print()
print(y)

[14 19 14 11 11 19 16 14  1 13]

[16 13 17 18 18 16 11 14 19  9]


In [66]:
#np.union1d()
print(np.union1d(x,y))

[ 1  9 11 13 14 16 17 18 19]


In [67]:
#np.intersection1d()
print(np.intersect1d(x,y))

[11 13 14 16 19]


In [68]:
#np.setdiff1d
print(np.setdiff1d(x,y))
print(np.setdiff1d(y,x))

[1]
[ 9 17 18]


In [69]:
#np.setxor1d() only give element unique in two arrays
print(np.setxor1d(x,y))

[ 1  9 17 18]


In [70]:
#np.in1d()
print(np.in1d(x,14))
print(np.in1d(y,14))

[ True False  True False False False False  True False False]
[False False False False False False False  True False False]
